### ISSUE TITLE
Babel-polyfill?

### ISSUE THREAD

**Issue by nono** [cozy/cozy-api#2]
Babel-polyfill is used to give polyfills for browsers that have not yet implemented the support of ES2015 features. It's pretty heavy and I don't think we aim support for browsers that have bad support of ES2015. So, it's probably a good idea to not include it in our build. Someone who wants to support these old browsers can include herself the polyfills.

**Comment by aenario** [comment]
Done in https://github.com/cozy/cozy-api/commit/0821feaca7596ad60c5a4421c0938b5ee6d34a9f.

I removed it from the bundle, but kept it for webpack-mocha as it makes tests more readable.
